name: Unit tests, build, test & publish container image

on:

  pull_request:

  push:

defaults:
  run:
    shell: bash

jobs:

  main:
    runs-on: ubuntu-latest

    steps:

    - name: Record build timestamp
      id: timestamp
      run: echo timestamp=$(date --rfc-3339=sec) >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        version: latest

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Construct PEP 440 version identifier
      id: pep_440
      run: echo version=$(uvx dunamai from git) >> $GITHUB_OUTPUT

    - name: Update project version identifier
      run: uv version "${{ steps.pep_440.outputs.version }}"

    - name: Install dependencies
      run: uv sync

    - name: Run unit tests
      run: uv run pytest --junit-xml=junit-default.xml

    - name: Build container image
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: Containerfile
        build-args: ''
        tags: localhost/ngfw-edl-server:latest
        labels: |
          org.opencontainers.image.authors=Sam Morris <sam@robots.org.uk>
          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.title=Next Generation Firewall Extended Dynamic List server
          org.opencontainers.image.created=${{ steps.timestamp.outputs.timestamp }}
          org.opencontainers.image.version=${{ steps.pep_440.outputs.version }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Run container tests
      run: uv run pytest -m container --junit-xml=junit-container.xml

    - name: Summarize test results
      uses: test-summary/action@v2
      with:
        paths: junit-*.xml
      if: always()

    - name: Tag container image
      run: buildah tag localhost/ngfw-edl-server:latest quay.io/yrro/ngfw-edl-server:latest

    - name: Push container image
      id: push
      uses: redhat-actions/push-to-registry@v2
      with:
        tags: quay.io/yrro/ngfw-edl-server:latest
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
