name: Run pre-commit hooks

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        version: latest

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.1
      env:
        SKIP: pip-audit,pytest

    - uses: pre-commit-ci/lite-action@v1.0.2
      if: always()
